first attempt for eatsSelf code
andrewoid/TouroSnake pull request #19
Opened 2020-09-09 21:14 UTC by shiraalter

I'm not sure if my logic is oversimplified and I'm still getting an error that I need a return statement but I just wanted to check if it's on the right track. Thanks!

2020-09-10 02:14 UTC, andrewoid commented
Your code doesn't compile. That's a large problem.

To tell if you're on the right track you need to write unit tests.

2020-09-10 03:04 UTC, rpeikes commented
If head hits the body, it wouldn't necessarily hit the fourth square. When the snake gets big it could the 10th for example. I think the logic just has to check if the head is intersecting with any other square in the the snake (but 2nd and 3rd would be impossible).

2020-09-10 22:10 UTC, rpeikes commented on src/main/java/touro/snake/Snake.java
> +        int headX = getHead().getX();
is getHead() a static method? Perhaps you need to instantiate or reference an instance of Snake?

2020-09-11 01:43 UTC, shweinfeld commented on src/main/java/touro/snake/Snake.java
> +        int headX = getHead().getX();
No. getHead() exists in the Snake itself. I used it for the move() method and it worked properly.

2020-09-11 01:45 UTC, shweinfeld commented
Perhaps you should create a variable that is set to 'true' or 'false' in the if/ else clause, and then return that variable.

2020-09-11 11:08 UTC, andrewoid requested changes

2020-09-11 11:08 UTC, andrewoid commented on src/test/java/touro/snake/SnakeTest.java
> +        SnakeHeadStateMachine headState = new SnakeHeadStateMachine(direction);
Instead of creating a new SnakeHeadStateMachine, create a mock instead

2020-09-11 11:08 UTC, andrewoid commented on src/test/java/touro/snake/SnakeTest.java
> +        List<Square> squareList = new ArrayList<>(snake.getSquares());
You are creating a new list of Squares, instead of using the list inside the Snake.

2020-09-15 15:30 UTC, shiraalter commented on src/test/java/touro/snake/SnakeTest.java
> +        Snake snake = new Snake(headStateMock);
The test failed when the Snake was a mock because it said the size of the list was 0. Why wouldn't it still run "createSnake()" and make the list?

2020-09-15 16:13 UTC, andrewoid commented on src/test/java/touro/snake/SnakeTest.java
> +        Snake snake = new Snake(headStateMock);
mocks don't run the constructor. Every method of a mock returns either 0, false or null depending on the return type.

2020-09-15 23:40 UTC, andrewoid commented on src/main/java/touro/snake/Snake.java
> +        int headX = this.getHead().getX();
Call getHead() only once.

2020-09-16 20:07 UTC, andrewoid commented
Please resolve the merge conflicts

2020-09-17 01:00 UTC, merged