Added score to Frame, getScore() method in Snake and test
andrewoid/TouroSnake pull request #31
Opened 2020-09-18 03:02 UTC by shiraalter

2020-09-18 03:40 UTC, shiraalter commented
One problem I found was that sometimes the food is placed in the row where the score label is and I can't reach it because I changed the bounds to detect the label as a boundary (and the food is blocked by it anyway). Need to fix that

2020-09-18 10:54 UTC, andrewoid commented on src/main/java/touro/snake/Snake.java
> +    //counter to keep track of score
This comment adds nothing.

2020-09-18 10:54 UTC, andrewoid commented on src/main/java/touro/snake/Snake.java
> +
scoreCounter++

2020-09-18 10:54 UTC, andrewoid commented on src/main/java/touro/snake/Snake.java
> +    //NEW METHOD
This comment doesn't add anything.

2020-09-18 10:54 UTC, andrewoid commented on src/main/java/touro/snake/SnakeFrame.java
> +        Timer timer = new Timer(0, scoreTracker);
Rather than using a Timer, can you find a way to update the score as a result of the snake eating the food?

2020-09-18 10:54 UTC, andrewoid commented on src/main/java/touro/snake/SnakeMain.java
> +        new SnakeFrame(gardenView, snakeKeyListener, snake).setVisible(true);       //added snake as parameter
No need to add comments like this.

2020-09-18 13:16 UTC, shiraalter commented on src/main/java/touro/snake/SnakeFrame.java
> +        Timer timer = new Timer(0, scoreTracker);
Even if it Already only increments when the snake eats the food?

2020-09-24 19:00 UTC, andrewoid requested changes
Use a Listener to detect that the score was changed instead of a Timer like we discussed in class.

2020-10-08 20:14 UTC, closed without merging