WIP: Trying to add second snake, program won't load
andrewoid/TouroSnake pull request #38
Opened 2020-09-21 20:22 UTC by ester-agishtein

2020-09-21 20:34 UTC, andrewoid commented on src/main/java/touro/snake/AIKeyListener.java
> +public class AIKeyListener extends KeyAdapter {
Copy and pasting code without understanding the code you are copying is highly dangerous.

What does a KeyAdapter do? Why is this a KeyAdapter?

2020-09-21 20:36 UTC, andrewoid commented
Perhaps you should use the debugger and try to figure out why the program doesn't load...

2020-09-22 06:51 UTC, ester-agishtein commented on src/main/java/touro/snake/AIKeyListener.java
> +public class AIKeyListener extends KeyAdapter {
I originally wasn't doing this and just trying to make some "change directions" methods but was having trouble getting the snake to show up. I was trying to keep as close to the original snake's work flow as possible but now realized my mistake and changing tactic.

2020-09-22 13:43 UTC, andrewoid commented on src/main/java/touro/snake/AIKeyListener.java
> +public class AIKeyListener{
Making sure code makes sense is important. This isn't a KeyListener so don't name it KeyListener

2020-09-22 13:55 UTC, andrewoid commented on src/test/java/touro/snake/SnakeTest.java
> +        Snake snake = mock(Snake.class);
You cannot test a mock.
If you are testing a Snake then it needs to be an actual Snake class

2020-09-23 23:43 UTC, andrewoid commented on src/main/java/touro/snake/AISnakeCreator.java
> +            Thread.sleep(DELAY_MS);
Why are you calling Thread.sleep?

2020-09-24 02:58 UTC, ester-agishtein commented on src/main/java/touro/snake/AISnakeCreator.java
> +            Thread.sleep(DELAY_MS);
I wanted to create a delay so the moving of the snake feels more natural

2020-09-29 15:31 UTC, andrewoid commented on src/main/java/touro/snake/GardenThread.java
> +                AISnakeCreator aiSnakeCreator = new AISnakeCreator(garden.getAiSnake());
Why are you recreating `AISnakeCreator` each time?

2020-09-29 15:32 UTC, andrewoid commented on src/main/java/touro/snake/Direction.java
> +    North("North"), East("East"), South("South"), West("West");
The "value" is not necessary.
`North.toString()` will give you the same String you're returning without it.

2020-09-29 15:34 UTC, andrewoid commented on src/main/java/touro/snake/AISnakeCreator.java
> +            Thread.sleep(DELAY_MS);
The game already updates every DELAY_MS. You are adding to the delay.

2020-09-29 15:36 UTC, andrewoid commented on src/main/java/touro/snake/AISnakeCreator.java
> +            String dirString = directions.get(randIndex);
You are turning `Direction.values()` into a `List<String>`, to get random Direction (as a String), then turning that String back into a Direction.

You should be able to do this without turning them into Strings.

2020-09-29 15:36 UTC, andrewoid commented on src/main/java/touro/snake/Garden.java
> +    public boolean advance(Snake snake) {
I'd rather you move both Snakes in the one `advance()` method.

2020-09-29 15:36 UTC, andrewoid requested changes
Lot of changes necessary.

2020-09-30 14:54 UTC, ester-agishtein commented on src/main/java/touro/snake/GardenThread.java
> +                AISnakeCreator aiSnakeCreator = new AISnakeCreator(garden.getAiSnake());
My bad, will move.

2020-09-30 15:02 UTC, ester-agishtein commented on src/main/java/touro/snake/AISnakeCreator.java
> +            Thread.sleep(DELAY_MS);
Is there a way for me to put some type of delay though? Without any it looks like it's on fire.

2020-09-30 15:04 UTC, ester-agishtein commented on src/main/java/touro/snake/Garden.java
> +    public boolean advance(Snake snake) {
So when I change this, (and this is a question just in general) sometimes the aisnake will go off the board. But we're going to have an infinite board. Is that bug something I should fix or just leave?

2020-10-06 18:51 UTC, andrewoid commented on src/main/java/touro/snake/AISnakeCreator.java
> +        int pick = new Random().nextInt(Direction.values().length);
Do not create a new `Random`.
Create it once and reuse it.

2020-10-06 18:51 UTC, andrewoid commented on src/main/java/touro/snake/Garden.java
> +    public Garden(Snake snake, Snake aiSnake, FoodFactory foodFactory) throws InterruptedException {
Why are you throwing `InterruptedException`

2020-10-06 18:52 UTC, andrewoid commented on src/main/java/touro/snake/Garden.java
> +        AISnakeCreator aiSnakeCreator = new AISnakeCreator(aiSnake);
What does this line do?

2020-10-06 18:53 UTC, andrewoid commented on src/main/java/touro/snake/AISnakeCreator.java
> +    public void moveSelf(Snake aiSnake) {
This doesn't actually move the Snake

2020-10-06 18:55 UTC, andrewoid commented on src/main/java/touro/snake/AISnakeCreator.java
> +public class AISnakeCreator {
What you call your classes matters.
If I saw a class named `AISnakeCreator` I would think that the class's purpose was to create the AI Snake. That's not what this class is doing.

2020-10-06 18:56 UTC, andrewoid commented on src/main/java/touro/snake/Garden.java
> +    public boolean advance(Snake snake) {
What stops the AI Snake from moving?

2020-10-08 20:20 UTC, closed without merging