Added poison
andrewoid/TouroSnake pull request #39
Opened 2020-09-21 20:42 UTC by dnagelCS

2020-09-23 18:28 UTC, andrewoid requested changes

2020-09-27 06:18 UTC, andrewoid commented on src/main/java/touro/snake/Snake.java
> +        if (drinksPoison(poison) && getSquares().size() >= 2) {
This is not the correct place to put the poison check

2020-09-29 15:37 UTC, andrewoid commented
Please fix the merge conflicts.

2020-10-06 22:38 UTC, andrewoid commented on src/main/java/touro/snake/Garden.java
> +        if (snake.drinksPoison(poison) && snake.getSquares().size() >= MIN_SIZE) {
I think the check on snake size is always going to be true here because of the previous if statement.

2020-10-06 22:38 UTC, andrewoid commented on src/main/java/touro/snake/Snake.java
> +        if (squares.contains(food) || squares.contains(poison)) {
Just return the conditional

2020-10-07 00:13 UTC, dnagelCS commented on src/test/java/touro/snake/GardenTest.java
> +    public void playSound() {
I don't know why this test isn't working for me as it worked for Orlian.

2020-10-07 01:26 UTC, dnagelCS commented on src/test/java/touro/snake/GardenTest.java
> +    public void playSound() {
I realized why. I am fixing it.

2020-11-04 17:34 UTC, closed without merging