added background music
andrewoid/TouroSnake pull request #40
Opened 2020-09-21 22:40 UTC by jkomendant

2020-09-21 23:44 UTC, andrewoid commented
Put the wave file in the resources directory

2020-09-22 00:35 UTC, jkomendant commented
> Put the wave file in the resources directory

Done

2020-09-23 18:30 UTC, andrewoid requested changes

2020-09-23 18:30 UTC, andrewoid commented on src/main/java/touro/snake/BackgroundSound.java
> +            Clip clip = AudioSystem.getClip();
this.clip = AudioSystem.getClip();

2020-09-23 19:19 UTC, jkomendant commented on src/main/java/touro/snake/BackgroundSound.java
> +            Clip clip = AudioSystem.getClip();
When I had done this.clip initially, clip got underlined in red. then i had moved it outside the playMusic method and I saw the request since the build failed. Should I put it back to how it was before by Clip clip = AudioSystem.getClip(); since it ran normally that way?

2020-09-23 19:20 UTC, jkomendant commented on src/main/java/touro/snake/BackgroundSound.java
> +            Clip clip = AudioSystem.getClip();
I was a bit confused about why I should change it to this.clip

2020-09-23 19:51 UTC, andrewoid commented on src/main/java/touro/snake/BackgroundSound.java
> +            Clip clip = AudioSystem.getClip();
The clip needs to be saved in the BackgroundSound class. Otherwise the OS might remove it from memory after you leave the playMusic() method.

2020-09-23 19:56 UTC, jkomendant commented on src/main/java/touro/snake/BackgroundSound.java
> +            Clip clip = AudioSystem.getClip();
What is this check failed notification that I got on both the new commits I pushed? Once when I split it up and then again when I put it back to the way it was before

2020-09-23 21:11 UTC, merged